export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const TYPE_OF_MODAL = "TYPE_OF_MODAL";
export const PAYPAL_AMOUNT="PAYPAL_AMOUNT";
export const MEMBERSHIP_MONTH="MEMBERSHIP_MONTH";
export const CURRENT_BILLING_PACKAGE="CURRENT_BILLING_PACKAGE";